name: "Build"

on:
  push:
    paths-ignore:
      - '**.md'
      - '.appveyor.yml'
      - '.editorconfig'
      - '.gitattributes'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - '**.md'
      - '.appveyor.yml'
      - '.editorconfig'
      - '.gitattributes'
      - 'LICENSE'
  # Allow manually triggering the workflow
  workflow_dispatch:

jobs:
  test:
    name: "Run the test suite"
    runs-on: "ubuntu-latest"
    continue-on-error: ${{ matrix.experimental == true }}

    strategy:
      matrix:
        php-version:
          - "5.3"
          - "5.4"
          - "5.5"
          - "5.6"
          - "7.0"
          - "7.1"
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
        tools:
          - "composer:v1"
          - "composer:v2"
        include:
          - php-version: "8.1"
            tools: "composer:v2"

          - php-version: "8.2"
            tools: "composer:v2"
            experimental: true

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          ini-values: "error_reporting=-1, display_errors=On, zend.assertions=1"
          tools: "${{ matrix.tools }}"
          php-version: "${{ matrix.php-version }}"

      - name: "Install dependencies"
        if: "matrix.php-version != '8.2'"
        run: "composer install --no-interaction --no-progress --prefer-dist"

      - name: "Install dependencies ignoring PHP requirement"
        if: "matrix.php-version == '8.2'"
        run: "composer update --no-interaction --no-progress --prefer-dist --ignore-platform-reqs"

      - name: "Check PHP syntax"
        run: "find src/ -type f -name '*.php' -print0 | xargs -0 -n1 -P4 -- php -l -f"

      - name: "Run the test suite"
        run: "composer test"

      - name: "Run the backward compatibility tests"
        if: "matrix.php-version == '8.0'"
        run: "composer test:bc"

  analysis:
    name: "Run static analysis"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          tools: "composer:v2, composer-normalize, phpstan"
          php-version: "8.0"

      - name: "Install dependencies"
        run: "composer install --no-interaction --no-progress --prefer-dist"

      - name: "Normalize composer.json"
        run: "composer-normalize --dry-run --no-check-lock --no-update-lock"

      - name: "PHPStan Analyse"
        run: "phpstan analyse --error-format=github"
