name: Qodana

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '.appveyor.yml'
      - '.editorconfig'
      - '.gitattributes'
      - '.github/workflows/build.yml'
      - 'LICENSE'
  # Allow manually triggering the workflow
  workflow_dispatch:

jobs:
  qodana:
    name: "Qodana analysis"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/work/_temp/_github_home/cache
          key: ${{ runner.os }}-qodana-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-qodana-${{ github.ref }}
            ${{ runner.os }}-qodana-
      - uses: docker://jetbrains/qodana-php
        with:
          args: --cache-dir=/github/home/cache --results-dir=/github/workspace/qodana --save-report --report-dir=/github/workspace/qodana/report
      - uses: actions/upload-artifact@v2
        with:
          path: qodana

#      - name: "Print check annotations"
#        run: cat ${{ github.workspace }}/qodana/*Inspection.json | jq --raw-output '.problems[] | "::\(if .problem_class.severity == "ERROR" then "error" else "warning" end) file=\(.file | sub(".{21}";"")),line=\(.line),pos=\(.offset)::\(.problem_class.name)%0A\(.description)"'
