name: Qodana

on: [push, pull_request]

jobs:
  qodana:
    name: "Qodana analysis"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          ini-values: "error_reporting=E_ALL, display_errors=On"
          tools: "composer:v2"
          php-version: "8.0"

      - name: "Install dependencies"
        run: "composer update --no-interaction --no-progress --prefer-dist --ignore-platform-reqs"

      - name: Qodana - Code Inspection
        uses: JetBrains/qodana-action@v2.0-eap
        with:
          results-dir: ${{ github.workspace }}/qodana

      - name: "Print check annotations"
        run: cat ${{ github.workspace }}/qodana/*Inspection.json | jq --raw-output '.problems[] | "::\(if .problem_class.severity == "ERROR" then "error" else "warning" end) file=\(.file | sub(".{21}";"")),line=\(.line),pos=\(.offset)::\(.problem_class.name)%0A\(.description)"'
